from os.path import join

DIRECTORY_RAW_DATA = "raw"
DIRECTORY_SBOM_BASE = "sboms"

DIRECTORY_NAME_SBOM_SPDX = "spdx"
DIRECTORY_PATH_SBOM_SPDX = join(DIRECTORY_SBOM_BASE, DIRECTORY_NAME_SBOM_SPDX)

DIRECTORY_NAME_SBOM_CYCLONEDX = "cyclonedx"
DIRECTORY_PATH_SBOM_CYCLONEDX = join(
    DIRECTORY_SBOM_BASE, DIRECTORY_NAME_SBOM_CYCLONEDX)

FILE_NAME_REQUIRED_RPMS = "required_rpms"
FILE_PATH_REQUIRED_RPMS = join(DIRECTORY_RAW_DATA, FILE_NAME_REQUIRED_RPMS)

FILE_NAME_REQUIRED_BY_RPMS = "required_by_rpms"
FILE_PATH_REQUIRED_BY_RPMS = join(
    DIRECTORY_RAW_DATA, FILE_NAME_REQUIRED_BY_RPMS)

FILE_NAME_ROOT_RPMS = "root_rpms"
FILE_PATH_ROOT_RPMS = join(DIRECTORY_RAW_DATA, FILE_NAME_ROOT_RPMS)

FILE_NAME_ALL_RPMS = "all_rpms"
FILE_PATH_ALL_RPMS = join(DIRECTORY_RAW_DATA, FILE_NAME_ALL_RPMS)
