name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypipublish:
    name: Publish SBOM4RPMs on PyPi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install python3-pip
          python3 -m pip install --upgrade pip setuptools wheel build

      - name: Build python package
        run: |
          python3 -m build
      
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          prerelease: false
          draft: false
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          files: |
            dist/*.whl
            dist/*.tar.gz

      - name: Publish SBOM4RPMs to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist/
